// Continuation spike: s00028g0f02 step=2 (10×10/16 RED, ~1.55B monolítico)
//
// Split: vi=9 (before var=11)
//   Chunk1: eliminates vars[0..9) = [1,2,3,4,5,6,7,8,10] — 9 variables
//   Checkpoint: 19 factors, 182 nonzero entries, ~999 felts (~32KB)
//   Chunk2: eliminates vars[9..27) = [11,14,...,91] — 18 variables
//
// Expected: ways0[10]=1, ways0[11]=2; final outcome mine=0, c0=1.
// Python verified (profile_ve_f22.py).

use zkmine_2g::ve::{
    count_ordinary_component, count_ordinary_component_start, count_ordinary_component_resume,
    Factor, FactorEntry, Constraint, NO_X_VAR,
};
use zkmine_2g::cell::{convolve_ordinary, apply_unconstrained_local, extract_outcomes};
use zkmine_2g::ve::JointEntry;
use zkmine_2g::bigint::{u512_zero, u512_eq, u512_from_u32};

// ─── Fixture data (f22: s00028g0f02 step=2) ──────────────────────────────────

fn f22_ord0_vars() -> Array<u32> {
    array![1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 14, 16, 18, 19, 20, 22, 26, 27, 28, 30, 40, 50, 60, 70, 80, 81, 91]
}

fn f22_ord0_constraints() -> Array<Constraint> {
    array![
        Constraint { variables: array![1, 2, 3, 11, 22], rhs: 1 },
        Constraint { variables: array![2, 3, 4, 14, 22], rhs: 2 },
        Constraint { variables: array![4, 5, 6, 14, 16, 26], rhs: 3 },
        Constraint { variables: array![6, 7, 8, 16, 18, 26, 27, 28], rhs: 5 },
        Constraint { variables: array![10, 11, 20, 22, 30], rhs: 1 },
        Constraint { variables: array![14], rhs: 1 },
        Constraint { variables: array![14, 16, 26], rhs: 3 },
        Constraint { variables: array![14, 22], rhs: 2 },
        Constraint { variables: array![18, 19, 28], rhs: 2 },
        Constraint { variables: array![20, 22, 30, 40], rhs: 1 },
        Constraint { variables: array![22], rhs: 1 },
        Constraint { variables: array![26], rhs: 1 },
        Constraint { variables: array![26, 27], rhs: 2 },
        Constraint { variables: array![26, 27, 28], rhs: 3 },
        Constraint { variables: array![27, 28], rhs: 2 },
        Constraint { variables: array![28], rhs: 1 },
        Constraint { variables: array![30, 40, 50], rhs: 1 },
        Constraint { variables: array![40, 50, 60], rhs: 1 },
        Constraint { variables: array![50, 60, 70], rhs: 1 },
        Constraint { variables: array![60, 70, 80, 81], rhs: 1 },
        Constraint { variables: array![81], rhs: 1 },
        Constraint { variables: array![81, 91], rhs: 2 },
    ]
}

/// Hardcoded checkpoint at vi=9 (before var=11).
/// Generated by scripts/profile_ve_f22.py.
/// 19 factors, 182 nonzero entries, ~999 felts.
fn f22_checkpoint_vi9() -> Array<Factor> {
    // Factor 0: scope=[14], 1 entry
    let f0 = Factor {
        scope_len: 1,
        variables: array![14],
        entries: array![FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 1: scope=[14, 16, 26], 1 entry
    let f1 = Factor {
        scope_len: 3,
        variables: array![14, 16, 26],
        entries: array![FactorEntry { mask: 7, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 2: scope=[14, 22], 1 entry
    let f2 = Factor {
        scope_len: 2,
        variables: array![14, 22],
        entries: array![FactorEntry { mask: 3, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 3: scope=[18, 19, 28], 3 entries
    let f3 = Factor {
        scope_len: 3,
        variables: array![18, 19, 28],
        entries: array![
            FactorEntry { mask: 3, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 5, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 6, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 4: scope=[20, 22, 30, 40], 4 entries
    let f4 = Factor {
        scope_len: 4,
        variables: array![20, 22, 30, 40],
        entries: array![
            FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 2, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 4, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 8, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 5: scope=[22], 1 entry
    let f5 = Factor {
        scope_len: 1,
        variables: array![22],
        entries: array![FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 6: scope=[26], 1 entry
    let f6 = Factor {
        scope_len: 1,
        variables: array![26],
        entries: array![FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 7: scope=[26, 27], 1 entry
    let f7 = Factor {
        scope_len: 2,
        variables: array![26, 27],
        entries: array![FactorEntry { mask: 3, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 8: scope=[26, 27, 28], 1 entry
    let f8 = Factor {
        scope_len: 3,
        variables: array![26, 27, 28],
        entries: array![FactorEntry { mask: 7, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 9: scope=[27, 28], 1 entry
    let f9 = Factor {
        scope_len: 2,
        variables: array![27, 28],
        entries: array![FactorEntry { mask: 3, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 10: scope=[28], 1 entry
    let f10 = Factor {
        scope_len: 1,
        variables: array![28],
        entries: array![FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 11: scope=[30, 40, 50], 3 entries
    let f11 = Factor {
        scope_len: 3,
        variables: array![30, 40, 50],
        entries: array![
            FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 2, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 4, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 12: scope=[40, 50, 60], 3 entries
    let f12 = Factor {
        scope_len: 3,
        variables: array![40, 50, 60],
        entries: array![
            FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 2, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 4, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 13: scope=[50, 60, 70], 3 entries
    let f13 = Factor {
        scope_len: 3,
        variables: array![50, 60, 70],
        entries: array![
            FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 2, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 4, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 14: scope=[60, 70, 80, 81], 4 entries
    let f14 = Factor {
        scope_len: 4,
        variables: array![60, 70, 80, 81],
        entries: array![
            FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 2, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 4, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 8, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 15: scope=[81], 1 entry
    let f15 = Factor {
        scope_len: 1,
        variables: array![81],
        entries: array![FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 16: scope=[81, 91], 1 entry
    let f16 = Factor {
        scope_len: 2,
        variables: array![81, 91],
        entries: array![FactorEntry { mask: 3, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }],
    };
    // Factor 17: scope=[11, 14, 16, 18, 22, 26, 27, 28], 146 entries
    // This is the large intermediate factor produced by eliminating vars 1-8 and 10.
    let f17 = Factor {
        scope_len: 8,
        variables: array![11, 14, 16, 18, 22, 26, 27, 28],
        entries: array![
            FactorEntry { mask: 12, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 28, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 14, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 30, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 40, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 56, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 42, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 58, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 44, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 60, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 46, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 62, mines: 2, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 68, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 84, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 70, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 86, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 72, mines: 6, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 88, mines: 5, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 74, mines: 5, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 75, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 90, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 76, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 92, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 78, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 94, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 76, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 92, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 78, mines: 4, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 79, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 94, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 96, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 112, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 98, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 114, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 100, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 116, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 102, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 118, mines: 2, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 104, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 120, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 106, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 122, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 104, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 120, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 106, mines: 4, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 107, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 122, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 108, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 124, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 110, mines: 2, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 126, mines: 1, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 132, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 148, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 134, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 150, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 136, mines: 6, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 152, mines: 5, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 138, mines: 5, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 139, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 154, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 140, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 156, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 142, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 158, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 140, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 156, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 142, mines: 4, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 143, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 158, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 160, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 176, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 162, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 178, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 164, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 180, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 166, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 182, mines: 2, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 168, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 184, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 170, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 186, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 168, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 184, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 170, mines: 4, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 171, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 186, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 172, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 188, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 174, mines: 2, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 190, mines: 1, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 192, mines: 6, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 208, mines: 5, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 194, mines: 5, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 195, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 210, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 196, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 212, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 198, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 214, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 196, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 212, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 198, mines: 4, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 199, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 214, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 200, mines: 5, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 216, mines: 4, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 202, mines: 4, x_mine: 0, nbrs: 0, count: 6_u256 },
            FactorEntry { mask: 203, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 218, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 202, mines: 5, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 203, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 204, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 220, mines: 2, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 206, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 222, mines: 1, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 204, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 220, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 206, mines: 3, x_mine: 0, nbrs: 0, count: 6_u256 },
            FactorEntry { mask: 207, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 222, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 224, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 240, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 226, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 242, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 224, mines: 5, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 240, mines: 4, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 226, mines: 4, x_mine: 0, nbrs: 0, count: 3_u256 },
            FactorEntry { mask: 227, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 242, mines: 3, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 228, mines: 3, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 244, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 230, mines: 2, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 246, mines: 1, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 232, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 248, mines: 2, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 234, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 250, mines: 1, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 232, mines: 4, x_mine: 0, nbrs: 0, count: 4_u256 },
            FactorEntry { mask: 248, mines: 3, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 234, mines: 3, x_mine: 0, nbrs: 0, count: 6_u256 },
            FactorEntry { mask: 235, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 250, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 236, mines: 2, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 252, mines: 1, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 238, mines: 1, x_mine: 0, nbrs: 0, count: 2_u256 },
            FactorEntry { mask: 254, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    // Factor 18: scope=[11, 20, 22, 30], 5 entries
    let f18 = Factor {
        scope_len: 4,
        variables: array![11, 20, 22, 30],
        entries: array![
            FactorEntry { mask: 0, mines: 1, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 1, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 2, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 4, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
            FactorEntry { mask: 8, mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 },
        ],
    };
    array![f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18]
}

// ─── Test 1: Monolithic ord0 (baseline gas measurement) ──────────────────────

#[test]
fn cont_f22_monolithic_ord0() {
    let ord0v = f22_ord0_vars();
    let ord0c = f22_ord0_constraints();
    let ways = count_ordinary_component(@ord0v, @ord0c);
    assert(*ways.at(10) == 1_u256, 'mono ways[10]');
    assert(*ways.at(11) == 2_u256, 'mono ways[11]');
}

// ─── Test 2: Chunk 1 — eliminate vars[0..9) = [1,2,3,4,5,6,7,8,10] ───────────

#[test]
fn cont_f22_chunk1() {
    let ord0v = f22_ord0_vars();
    let ord0c = f22_ord0_constraints();
    // Split at vi=9: process the first 9 variables
    let factors = count_ordinary_component_start(@ord0v, @ord0c, 9);
    // Checkpoint: 19 factors remaining
    assert(factors.len() == 19, 'chunk1 factor count');
}

// ─── Test 3: Chunk 2 — resume from hardcoded checkpoint (vi=9) ───────────────

#[test]
fn cont_f22_chunk2_hardcoded() {
    let ord0v = f22_ord0_vars();
    let checkpoint = f22_checkpoint_vi9();
    // Resume from start_idx=9 (variable 11 and beyond)
    let ways = count_ordinary_component_resume(@ord0v, checkpoint, 9);
    assert(*ways.at(10) == 1_u256, 'chunk2 ways[10]');
    assert(*ways.at(11) == 2_u256, 'chunk2 ways[11]');
}

// ─── Test 4: Full CELL with continuation (exact outcome verification) ─────────

#[test]
fn cont_f22_full_cell_exact() {
    let ord0v = f22_ord0_vars();
    let checkpoint = f22_checkpoint_vi9();

    // Chunk 2: resume ord0 from checkpoint
    let ord0w = count_ordinary_component_resume(@ord0v, checkpoint, 9);

    // Start aggregate (no special component)
    let mut aggregate: Array<JointEntry> = array![
        JointEntry { mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }
    ];
    aggregate = convolve_ordinary(@aggregate, @ord0w);

    // ord1: var=53, constraint [53]:rhs=1
    let ord1v: Array<u32> = array![53];
    let ord1c: Array<Constraint> = array![Constraint { variables: array![53], rhs: 1 }];
    let ord1w = count_ordinary_component(@ord1v, @ord1c);
    aggregate = convolve_ordinary(@aggregate, @ord1w);

    // ord2: vars=[59,69]
    let ord2v: Array<u32> = array![59, 69];
    let ord2c: Array<Constraint> = array![
        Constraint { variables: array![59], rhs: 1 },
        Constraint { variables: array![59, 69], rhs: 2 },
        Constraint { variables: array![69], rhs: 1 },
    ];
    let ord2w = count_ordinary_component(@ord2v, @ord2c);
    aggregate = convolve_ordinary(@aggregate, @ord2w);

    // ord3: vars=[76,95,96,97]
    let ord3v: Array<u32> = array![76, 95, 96, 97];
    let ord3c: Array<Constraint> = array![
        Constraint { variables: array![76], rhs: 1 },
        Constraint { variables: array![76, 95, 96], rhs: 2 },
        Constraint { variables: array![76, 95, 96, 97], rhs: 3 },
        Constraint { variables: array![76, 96, 97], rhs: 2 },
        Constraint { variables: array![95], rhs: 1 },
        Constraint { variables: array![97], rhs: 1 },
    ];
    let ord3w = count_ordinary_component(@ord3v, @ord3c);
    aggregate = convolve_ordinary(@aggregate, @ord3w);

    // Extract outcomes: remaining_mines=16, unc_other=3, adj_known_mines=0
    let outcomes = extract_outcomes(@aggregate, 16, 3, 0);

    // Expected: mine=0, c0=1, c1..c8=0 (matches Cairo exact test sq10_exact_f22)
    assert(u512_eq(*outcomes.at(0), u512_zero()), 'mine=0');
    assert(u512_eq(*outcomes.at(1), u512_from_u32(1)), 'c0=1');
    assert(u512_eq(*outcomes.at(2), u512_zero()), 'c1=0');
    assert(u512_eq(*outcomes.at(3), u512_zero()), 'c2=0');
    assert(u512_eq(*outcomes.at(4), u512_zero()), 'c3=0');
    assert(u512_eq(*outcomes.at(5), u512_zero()), 'c4=0');
    assert(u512_eq(*outcomes.at(6), u512_zero()), 'c5=0');
    assert(u512_eq(*outcomes.at(7), u512_zero()), 'c6=0');
    assert(u512_eq(*outcomes.at(8), u512_zero()), 'c7=0');
    assert(u512_eq(*outcomes.at(9), u512_zero()), 'c8=0');
}

// ─── Test 6: Serde round-trip + chunk2 ───────────────────────────────────────
// Serializes the hardcoded checkpoint to Array<felt252> (simulating calldata),
// deserializes it, and runs chunk2. Proves the checkpoint is Serde-compatible
// and that a real Starknet calldata bridge would work.

#[test]
fn cont_f22_serde_roundtrip_chunk2() {
    // Serialize checkpoint → Array<felt252>
    let checkpoint = f22_checkpoint_vi9();
    let mut buf: Array<felt252> = array![];
    Serde::serialize(@checkpoint, ref buf);

    // Deserialize back → Array<Factor>
    let mut span = buf.span();
    let recovered: Option<Array<Factor>> = Serde::deserialize(ref span);
    assert(recovered.is_some(), 'serde deserialize failed');
    let recovered = recovered.unwrap();

    // Run chunk2 with deserialized checkpoint
    let ord0v = f22_ord0_vars();
    let ways = count_ordinary_component_resume(@ord0v, recovered, 9);
    assert(*ways.at(10) == 1_u256, 'serde ways[10]');
    assert(*ways.at(11) == 2_u256, 'serde ways[11]');
}

// ─── Test 5: Chunk1 result equals monolithic result ───────────────────────────
// Verifies that chunk1→chunk2 composed gives same ways as monolithic.

#[test]
fn cont_f22_chunk2_inline_compose() {
    let ord0v = f22_ord0_vars();
    let ord0c = f22_ord0_constraints();

    // Chunk 1: get checkpoint
    let checkpoint = count_ordinary_component_start(@ord0v, @ord0c, 9);
    assert(checkpoint.len() == 19, 'compose checkpoint len');

    // Chunk 2: resume from checkpoint (composed in same call)
    let ways_cont = count_ordinary_component_resume(@ord0v, checkpoint, 9);

    // Monolithic baseline
    let ord0v2 = f22_ord0_vars();
    let ord0c2 = f22_ord0_constraints();
    let ways_mono = count_ordinary_component(@ord0v2, @ord0c2);

    // Verify identical results
    assert(ways_cont.len() == ways_mono.len(), 'ways len match');
    assert(*ways_cont.at(10) == *ways_mono.at(10), 'ways[10] match');
    assert(*ways_cont.at(11) == *ways_mono.at(11), 'ways[11] match');
    // Verify all entries match
    let mut ki: usize = 0;
    loop {
        if ki >= ways_mono.len() { break; }
        assert(*ways_cont.at(ki) == *ways_mono.at(ki), 'ways[k] match');
        ki += 1;
    };
}
