#!/usr/bin/env python3
"""
Phase 8 Cairo test generator: flood-fill CELL sequence gas benchmark.

Reads benchmarks/2g-phase8-fixtures-20260831.jsonl and generates:
  contracts/zkmine_2g/src/tests/test_ve_phase8.cairo        — benchmark (no outcome asserts)
  contracts/zkmine_2g/src/tests/test_ve_phase8_exact.cairo  — correctness (all 10 outcomes)
  contracts/zkmine_2g/src/tests/test_ve_phase8_combined.cairo — combined per-flood (selected floods)

Test naming:
  benchmark:  p8_f{flood_idx:02d}_s{step:03d}
  exact:      p8_exact_f{flood_idx:02d}_s{step:03d}
  combined:   p8_combined_f{flood_idx:02d}

Pattern for snforge:
  benchmark:  snforge test "p8_f"          (does NOT match p8_exact_f)
  exact:      snforge test "p8_exact_f"
  combined:   snforge test "p8_combined"
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

FIXTURES_PATH   = Path("benchmarks/2g-phase8-fixtures-20260831.jsonl")
BENCH_PATH      = Path("contracts/zkmine_2g/src/tests/test_ve_phase8.cairo")
EXACT_PATH      = Path("contracts/zkmine_2g/src/tests/test_ve_phase8_exact.cairo")
COMBINED_PATH   = Path("contracts/zkmine_2g/src/tests/test_ve_phase8_combined.cairo")

BENCH_HEADER = """\
// AUTO-GENERATED by gen_phase8_cairo_tests.py — do not edit by hand
// Phase 8 gas benchmark: full CELL pipeline per flood step, no outcome assertions.

use zkmine_2g::ve::{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry};
use zkmine_2g::cell::{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes};

"""

EXACT_HEADER = """\
// AUTO-GENERATED by gen_phase8_cairo_tests.py — do not edit by hand
// Phase 8 correctness: full CELL pipeline with all 10 outcome assertions.

use zkmine_2g::ve::{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry};
use zkmine_2g::cell::{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes};
use zkmine_2g::bigint::u512_eq;
use core::integer::u512;

"""

COMBINED_HEADER = """\
// AUTO-GENERATED by gen_phase8_cairo_tests.py — do not edit by hand
// Phase 8 combined: all CELL steps of selected floods in one test each.

use zkmine_2g::ve::{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry};
use zkmine_2g::cell::{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes};

"""


def int_to_u512(n: int) -> str:
    n = int(n)
    mask = (1 << 128) - 1
    l0 = n & mask
    l1 = (n >> 128) & mask
    l2 = (n >> 256) & mask
    l3 = (n >> 384) & mask
    return f"u512 {{ limb0: {l0}, limb1: {l1}, limb2: {l2}, limb3: {l3} }}"


def fmt_constraint(c: dict) -> str:
    scope = ", ".join(str(v) for v in c["scope"])
    return f"Constraint {{ variables: array![{scope}], rhs: {c['rhs']} }}"


def fmt_u32_array(vals) -> str:
    return "array![" + ", ".join(str(v) for v in vals) + "]"


def cell_pipeline_lines(fix: dict, prefix: str = "", underscore_outcomes: bool = True) -> list[str]:
    """Return lines for one CELL pipeline (inside a function body)."""
    lines: list[str] = []
    out_var = "_outcomes" if underscore_outcomes else "outcomes"
    rm  = fix["remaining_mines"]
    uo  = fix["unconstrained_other_count"]
    akm = fix["adjacent_known_mines"]
    unc = fix["unconstrained_local"]
    sps = fix.get("special_components", [])

    step_num = 1

    # Step 1: joint VE for each special component, then convolve if multiple
    if sps:
        for si, sp in enumerate(sps):
            sp_vars_str   = fmt_u32_array(sp["variables"])
            sp_constr_str = "array![" + ", ".join(fmt_constraint(c) for c in sp["constraints"]) + "]"
            sp_hint_str   = fmt_u32_array(sp["min_fill_order"])
            sp_nbrs_str   = fmt_u32_array(sp["neighbor_vars"])
            x_var = sp["x_var"]
            tag = f"sp{si}" if len(sps) > 1 else "sp"
            lines.append(f"    // Step {step_num}: joint VE on special component {si} (size={len(sp['variables'])} width={sp['min_fill_width']})")
            lines.append(f"    let {tag}_vars{prefix}: Array<u32> = {sp_vars_str};")
            lines.append(f"    let {tag}_constr{prefix}: Array<Constraint> = {sp_constr_str};")
            lines.append(f"    let {tag}_hint{prefix}: Array<u32> = {sp_hint_str};")
            lines.append(f"    let {tag}_nbrs{prefix}: Array<u32> = {sp_nbrs_str};")
            lines.append(f"    let {tag}_entries{prefix}: Array<JointEntry> = count_joint_component_with_order(@{tag}_vars{prefix}, @{tag}_constr{prefix}, {x_var}, @{tag}_nbrs{prefix}, @{tag}_hint{prefix});")
            step_num += 1
        if len(sps) == 1:
            lines.append(f"    let mut aggregate{prefix}: Array<JointEntry> = sp_entries{prefix};")
        else:
            lines.append(f"    let mut aggregate{prefix}: Array<JointEntry> = convolve_joint(@sp0_entries{prefix}, @sp1_entries{prefix});")
            for si in range(2, len(sps)):
                lines.append(f"    aggregate{prefix} = convolve_joint(@aggregate{prefix}, @sp{si}_entries{prefix});")
    else:
        lines.append(f"    // No special component — cell fully surrounded by known cells")
        lines.append(f"    let mut aggregate{prefix}: Array<JointEntry> = array![JointEntry {{ mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }}];")

    # Ordinary components
    for oi, oc in enumerate(fix["ordinary_components"]):
        ov = fmt_u32_array(oc["variables"])
        oc_str = "array![" + ", ".join(fmt_constraint(c) for c in oc["constraints"]) + "]"
        lines.append(f"    // Step {step_num}.{oi}: ordinary component {oi} (size={len(oc['variables'])})")
        lines.append(f"    let ord{oi}v{prefix}: Array<u32> = {ov};")
        lines.append(f"    let ord{oi}c{prefix}: Array<Constraint> = {oc_str};")
        lines.append(f"    let ord{oi}w{prefix} = count_ordinary_component(@ord{oi}v{prefix}, @ord{oi}c{prefix});")
        lines.append(f"    aggregate{prefix} = convolve_ordinary(@aggregate{prefix}, @ord{oi}w{prefix});")
        if oi == 0:
            step_num += 1

    # Unconstrained local
    if unc["has"]:
        n_unc = unc["neighbor_count"]
        lines.append(f"    // Step {step_num + len(fix['ordinary_components'])}: unconstrained local (neighbors={n_unc})")
        lines.append(f"    aggregate{prefix} = apply_unconstrained_local(@aggregate{prefix}, false, {n_unc});")

    # Extract outcomes
    lines.append(f"    let {out_var}{prefix} = extract_outcomes(@aggregate{prefix}, {rm}, {uo}, {akm});")

    return lines


def bench_test(fix: dict, test_name: str) -> str:
    sps  = fix.get("special_components", [])
    oc   = fix["ordinary_components"]
    unc  = fix["unconstrained_local"]
    max_width = max((sp["min_fill_width"] for sp in sps), default=0)
    comment = (
        f"CELL gas: flood={fix['flood_id']} step={fix['step']} wave={fix['wave_index']}"
        f" size={max_width}"
        f" ord={len(oc)}"
        f" unc_loc={unc['neighbor_count']}"
        f" unc_oth={fix['unconstrained_other_count']}"
    )
    body = cell_pipeline_lines(fix, underscore_outcomes=True)
    return (
        f"#[test]\n"
        f"// {comment}\n"
        f"fn {test_name}() {{\n"
        + "\n".join(body) + "\n"
        f"}}\n"
    )


def exact_test(fix: dict, test_name: str) -> str:
    body = cell_pipeline_lines(fix, underscore_outcomes=False)
    eo   = fix["expected_outcomes"]
    case_label = f"{fix['flood_id']}_s{fix['step']:03d}"

    asserts = []
    asserts.append(f"    assert(u512_eq(*outcomes.at(0), {int_to_u512(int(eo['mine']))}), '{case_label} mine');")
    for i in range(9):
        val = int(eo.get(str(i), 0))
        asserts.append(f"    assert(u512_eq(*outcomes.at({i+1}), {int_to_u512(val)}), '{case_label} c{i}');")

    return (
        f"#[test]\n"
        f"// CELL exact: flood={fix['flood_id']} step={fix['step']}\n"
        f"fn {test_name}() {{\n"
        + "\n".join(body) + "\n"
        + "\n".join(asserts) + "\n"
        f"}}\n"
    )


def combined_test(flood_id: str, flood_index: int, fixes: list[dict]) -> str:
    lines: list[str] = []
    for i, fix in enumerate(fixes):
        pfx = f"_s{fix['step']:03d}"
        lines.append(f"    // Cell step {fix['step']}: cell_index={fix['cell_index']} wave={fix['wave_index']}")
        lines.append("    {")
        inner = cell_pipeline_lines(fix, prefix=pfx, underscore_outcomes=True)
        for ln in inner:
            lines.append("    " + ln.strip())
        lines.append("    }")
    return (
        f"#[test]\n"
        f"// COMBINED flood={flood_id} steps={len(fixes)}\n"
        f"fn p8_combined_f{flood_index:02d}() {{\n"
        + "\n".join(lines) + "\n"
        f"}}\n"
    )


def main() -> None:
    with open(FIXTURES_PATH) as f:
        all_fixtures = [json.loads(l) for l in f if l.strip()]

    # Group by flood_index
    floods: dict[int, list[dict]] = {}
    for fix in all_fixtures:
        fi = fix["flood_index"]
        floods.setdefault(fi, []).append(fix)
    for fi in floods:
        floods[fi].sort(key=lambda x: x["step"])

    n_floods = len(floods)
    total_cells = sum(len(v) for v in floods.values())
    print(f"Floods: {n_floods}, total CELL steps: {total_cells}", file=sys.stderr)

    # Benchmark and exact test files
    bench_lines = [BENCH_HEADER]
    exact_lines = [EXACT_HEADER]

    for flood_index in sorted(floods.keys()):
        fixes = floods[flood_index]
        for fix in fixes:
            step = fix["step"]
            tname_bench = f"p8_f{flood_index:02d}_s{step:03d}"
            tname_exact = f"p8_exact_f{flood_index:02d}_s{step:03d}"
            bench_lines.append(bench_test(fix, tname_bench))
            exact_lines.append(exact_test(fix, tname_exact))

    BENCH_PATH.write_text("".join(bench_lines))
    EXACT_PATH.write_text("".join(exact_lines))
    print(f"Written {BENCH_PATH} ({BENCH_PATH.stat().st_size // 1024} KB)", file=sys.stderr)
    print(f"Written {EXACT_PATH} ({EXACT_PATH.stat().st_size // 1024} KB)", file=sys.stderr)

    # Combined tests: choose 3 floods (cheapest, median, most expensive by step count)
    step_counts = {fi: len(fixes) for fi, fixes in floods.items()}
    sorted_by_steps = sorted(step_counts.items(), key=lambda x: x[1])
    n = len(sorted_by_steps)
    selected_indices = [
        sorted_by_steps[0][0],           # cheapest (fewest steps)
        sorted_by_steps[n // 2][0],      # median
        sorted_by_steps[-1][0],          # most expensive (most steps)
    ]
    # Deduplicate
    seen: set[int] = set()
    selected_unique = []
    for idx in selected_indices:
        if idx not in seen:
            seen.add(idx)
            selected_unique.append(idx)

    combined_lines = [COMBINED_HEADER]
    for fi in selected_unique:
        fixes = floods[fi]
        flood_id = fixes[0]["flood_id"]
        combined_lines.append(combined_test(flood_id, fi, fixes))

    COMBINED_PATH.write_text("".join(combined_lines))
    print(
        f"Written {COMBINED_PATH} "
        f"(combined floods: {selected_unique}, steps: {[len(floods[i]) for i in selected_unique]})",
        file=sys.stderr,
    )

    # Summary
    print(f"\nTest counts: benchmark={total_cells} exact={total_cells} combined={len(selected_unique)}", file=sys.stderr)
    print(f"Run patterns:", file=sys.stderr)
    print(f"  snforge test \"p8_f\"        → {total_cells} benchmark", file=sys.stderr)
    print(f"  snforge test \"p8_exact_f\"  → {total_cells} exact", file=sys.stderr)
    print(f"  snforge test \"p8_combined\" → {len(selected_unique)} combined", file=sys.stderr)


if __name__ == "__main__":
    main()
