#!/usr/bin/env python3
"""
gen_square_cairo_tests.py

Genera tests Cairo (benchmark + exact) para candidatos NxN/M.
Parametrizado con --size N --mines M.

Test naming:
  benchmark: sq{N}_f{i:02d}
  exact:     sq{N}_exact_f{i:02d}

Inputs:
  benchmarks/square-{N}x{N}-{M}-fixtures-{DATE}.jsonl

Outputs:
  contracts/zkmine_2g/src/tests/test_ve_sq{N}x{N}.cairo
  contracts/zkmine_2g/src/tests/test_ve_sq{N}x{N}_exact.cairo
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATE = "20260901"

BENCH_HEADER_TMPL = """\
// AUTO-GENERATED by gen_square_cairo_tests.py — do not edit by hand
// Square {N}x{N}/{M} gas benchmark: full CELL pipeline, no outcome assertions.

use zkmine_2g::ve::{{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry}};
use zkmine_2g::cell::{{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes}};

"""

EXACT_HEADER_TMPL = """\
// AUTO-GENERATED by gen_square_cairo_tests.py — do not edit by hand
// Square {N}x{N}/{M} correctness: full CELL pipeline with all 10 outcome assertions.

use zkmine_2g::ve::{{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry}};
use zkmine_2g::cell::{{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes}};
use zkmine_2g::bigint::u512_eq;
use core::integer::u512;

"""


def mines_for_size(n: int) -> int:
    return math.floor(5 * n * n / 32 + 0.5)


def int_to_u512(n: int) -> str:
    n = int(n)
    mask = (1 << 128) - 1
    l0 = n & mask
    l1 = (n >> 128) & mask
    l2 = (n >> 256) & mask
    l3 = (n >> 384) & mask
    return f"u512 {{ limb0: {l0}, limb1: {l1}, limb2: {l2}, limb3: {l3} }}"


def fmt_constraint(c: dict) -> str:
    scope = ", ".join(str(v) for v in c["scope"])
    return f"Constraint {{ variables: array![{scope}], rhs: {c['rhs']} }}"


def fmt_u32_array(vals) -> str:
    return "array![" + ", ".join(str(v) for v in vals) + "]"


def cell_pipeline_lines(fix: dict, underscore_outcomes: bool = True) -> list[str]:
    lines: list[str] = []
    out_var = "_outcomes" if underscore_outcomes else "outcomes"
    rm  = fix["remaining_mines"]
    uo  = fix["unconstrained_other_count"]
    akm = fix["adjacent_known_mines"]
    unc = fix["unconstrained_local"]
    sps = fix.get("special_components", [])

    step_num = 1

    if sps:
        for si, sp in enumerate(sps):
            sp_vars_str   = fmt_u32_array(sp["variables"])
            sp_constr_str = "array![" + ", ".join(fmt_constraint(c) for c in sp["constraints"]) + "]"
            sp_hint_str   = fmt_u32_array(sp["min_fill_order"])
            sp_nbrs_str   = fmt_u32_array(sp["neighbor_vars"])
            x_var = sp["x_var"]
            tag = f"sp{si}" if len(sps) > 1 else "sp"
            lines.append(
                f"    // Step {step_num}: joint VE special {si} "
                f"(size={len(sp['variables'])} width={sp['min_fill_width']})"
            )
            lines.append(f"    let {tag}_vars: Array<u32> = {sp_vars_str};")
            lines.append(f"    let {tag}_constr: Array<Constraint> = {sp_constr_str};")
            lines.append(f"    let {tag}_hint: Array<u32> = {sp_hint_str};")
            lines.append(f"    let {tag}_nbrs: Array<u32> = {sp_nbrs_str};")
            lines.append(
                f"    let {tag}_entries: Array<JointEntry> = "
                f"count_joint_component_with_order(@{tag}_vars, @{tag}_constr, "
                f"{x_var}, @{tag}_nbrs, @{tag}_hint);"
            )
            step_num += 1
        if len(sps) == 1:
            lines.append(f"    let mut aggregate: Array<JointEntry> = sp_entries;")
        else:
            lines.append(f"    let mut aggregate: Array<JointEntry> = convolve_joint(@sp0_entries, @sp1_entries);")
            for si in range(2, len(sps)):
                lines.append(f"    aggregate = convolve_joint(@aggregate, @sp{si}_entries);")
    else:
        lines.append(f"    // No special component")
        lines.append(
            f"    let mut aggregate: Array<JointEntry> = "
            f"array![JointEntry {{ mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }}];"
        )

    for oi, oc in enumerate(fix["ordinary_components"]):
        ov = fmt_u32_array(oc["variables"])
        oc_str = "array![" + ", ".join(fmt_constraint(c) for c in oc["constraints"]) + "]"
        lines.append(f"    // ordinary {oi} (size={len(oc['variables'])})")
        lines.append(f"    let ord{oi}v: Array<u32> = {ov};")
        lines.append(f"    let ord{oi}c: Array<Constraint> = {oc_str};")
        lines.append(f"    let ord{oi}w = count_ordinary_component(@ord{oi}v, @ord{oi}c);")
        lines.append(f"    aggregate = convolve_ordinary(@aggregate, @ord{oi}w);")
        if oi == 0:
            step_num += 1

    if unc["has"]:
        n_unc = unc["neighbor_count"]
        lines.append(f"    // unconstrained local neighbors={n_unc}")
        lines.append(f"    aggregate = apply_unconstrained_local(@aggregate, false, {n_unc});")

    lines.append(f"    let {out_var} = extract_outcomes(@aggregate, {rm}, {uo}, {akm});")

    return lines


def bench_test(fix: dict, test_name: str) -> str:
    sps = fix.get("special_components", [])
    oc  = fix["ordinary_components"]
    unc = fix["unconstrained_local"]
    max_width = max((sp["min_fill_width"] for sp in sps), default=0)
    comment = (
        f"CELL gas: id={fix['flood_id']} step={fix['step']} wave={fix['wave_index']}"
        f" w={max_width} ord={len(oc)} unc_loc={unc['neighbor_count']}"
        f" unc_oth={fix['unconstrained_other_count']}"
    )
    body = cell_pipeline_lines(fix, underscore_outcomes=True)
    return (
        f"#[test]\n"
        f"// {comment}\n"
        f"fn {test_name}() {{\n"
        + "\n".join(body) + "\n"
        f"}}\n"
    )


def exact_test(fix: dict, test_name: str) -> str:
    body = cell_pipeline_lines(fix, underscore_outcomes=False)
    eo = fix["expected_outcomes"]
    case_label = f"{fix['flood_id']}_s{fix['step']:03d}"

    asserts = []
    asserts.append(
        f"    assert(u512_eq(*outcomes.at(0), {int_to_u512(int(eo['mine']))}), '{case_label} mine');"
    )
    for i in range(9):
        val = int(eo.get(str(i), 0))
        asserts.append(
            f"    assert(u512_eq(*outcomes.at({i+1}), {int_to_u512(val)}), '{case_label} c{i}');"
        )

    return (
        f"#[test]\n"
        f"// CELL exact: id={fix['flood_id']} step={fix['step']}\n"
        f"fn {test_name}() {{\n"
        + "\n".join(body) + "\n"
        + "\n".join(asserts) + "\n"
        f"}}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--size",    type=int, required=True)
    parser.add_argument("--mines",   type=int, default=-1)
    parser.add_argument("--run-tag", type=str, default="", help="Optional tag for replication runs (e.g. rep2)")
    args = parser.parse_args()

    N = args.size
    M = args.mines if args.mines >= 0 else mines_for_size(N)
    tag_infix = f"-{args.run_tag}" if args.run_tag else ""
    tag_suffix = f"_{args.run_tag}" if args.run_tag else ""

    fixtures_path = REPO_ROOT / "benchmarks" / f"square-{N}x{N}-{M}{tag_infix}-fixtures-{DATE}.jsonl"
    bench_path    = REPO_ROOT / "contracts/zkmine_2g/src/tests" / f"test_ve_sq{N}x{N}{tag_suffix}.cairo"
    exact_path    = REPO_ROOT / "contracts/zkmine_2g/src/tests" / f"test_ve_sq{N}x{N}{tag_suffix}_exact.cairo"

    fixtures: list[dict] = []
    with open(fixtures_path) as f:
        for line in f:
            if line.strip():
                fixtures.append(json.loads(line))
    fixtures.sort(key=lambda x: x["flood_index"])
    print(f"Loaded {len(fixtures)} fixtures", file=sys.stderr)

    bench_header = BENCH_HEADER_TMPL.format(N=N, M=M)
    exact_header = EXACT_HEADER_TMPL.format(N=N, M=M)

    bench_lines = [bench_header]
    exact_lines = [exact_header]

    prefix = f"sq{N}{tag_suffix}"
    for fix in fixtures:
        fi = fix["flood_index"]
        tname_bench = f"{prefix}_f{fi:02d}"
        tname_exact = f"{prefix}_exact_f{fi:02d}"
        bench_lines.append(bench_test(fix, tname_bench))
        exact_lines.append(exact_test(fix, tname_exact))

    bench_path.write_text("".join(bench_lines))
    exact_path.write_text("".join(exact_lines))

    print(f"Written {bench_path} ({bench_path.stat().st_size // 1024} KB)", file=sys.stderr)
    print(f"Written {exact_path} ({exact_path.stat().st_size // 1024} KB)", file=sys.stderr)
    print(f"\nRun with:", file=sys.stderr)
    print(f"  snforge test \"{prefix}_f\"        → {len(fixtures)} benchmark tests", file=sys.stderr)
    print(f"  snforge test \"{prefix}_exact_f\"   → {len(fixtures)} exact tests", file=sys.stderr)


if __name__ == "__main__":
    main()
