#!/usr/bin/env python3
"""
gen_intermediate_cairo_tests.py

Genera tests Cairo (benchmark + exact) para los 59 candidatos Intermediate 16×16/40.
Reutiliza el patrón de gen_phase8_cairo_tests.py.

Test naming:
  benchmark: im_f{i:02d}   (gas measurement, sin assertions de outcome)
  exact:     im_exact_f{i:02d}  (correctness: 10 outcome assertions)

Inputs:
  benchmarks/intermediate-16x16-40-fixtures-20260901.jsonl  (59 fixtures)

Outputs:
  contracts/zkmine_2g/src/tests/test_ve_intermediate.cairo
  contracts/zkmine_2g/src/tests/test_ve_intermediate_exact.cairo
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

FIXTURES_PATH = REPO_ROOT / "benchmarks" / "intermediate-16x16-40-fixtures-20260901.jsonl"
BENCH_PATH    = REPO_ROOT / "contracts/zkmine_2g/src/tests/test_ve_intermediate.cairo"
EXACT_PATH    = REPO_ROOT / "contracts/zkmine_2g/src/tests/test_ve_intermediate_exact.cairo"

BENCH_HEADER = """\
// AUTO-GENERATED by gen_intermediate_cairo_tests.py — do not edit by hand
// Intermediate 16x16/40 gas benchmark: full CELL pipeline, no outcome assertions.

use zkmine_2g::ve::{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry};
use zkmine_2g::cell::{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes};

"""

EXACT_HEADER = """\
// AUTO-GENERATED by gen_intermediate_cairo_tests.py — do not edit by hand
// Intermediate 16x16/40 correctness: full CELL pipeline with all 10 outcome assertions.

use zkmine_2g::ve::{count_joint_component_with_order, count_ordinary_component, Constraint, JointEntry};
use zkmine_2g::cell::{convolve_joint, convolve_ordinary, apply_unconstrained_local, extract_outcomes};
use zkmine_2g::bigint::u512_eq;
use core::integer::u512;

"""


def int_to_u512(n: int) -> str:
    n = int(n)
    mask = (1 << 128) - 1
    l0 = n & mask
    l1 = (n >> 128) & mask
    l2 = (n >> 256) & mask
    l3 = (n >> 384) & mask
    return f"u512 {{ limb0: {l0}, limb1: {l1}, limb2: {l2}, limb3: {l3} }}"


def fmt_constraint(c: dict) -> str:
    scope = ", ".join(str(v) for v in c["scope"])
    return f"Constraint {{ variables: array![{scope}], rhs: {c['rhs']} }}"


def fmt_u32_array(vals) -> str:
    return "array![" + ", ".join(str(v) for v in vals) + "]"


def cell_pipeline_lines(fix: dict, underscore_outcomes: bool = True) -> list[str]:
    """Return Cairo lines for one full CELL pipeline (inside a function body)."""
    lines: list[str] = []
    out_var = "_outcomes" if underscore_outcomes else "outcomes"
    rm  = fix["remaining_mines"]
    uo  = fix["unconstrained_other_count"]
    akm = fix["adjacent_known_mines"]
    unc = fix["unconstrained_local"]
    sps = fix.get("special_components", [])

    step_num = 1

    # Special components (joint VE)
    if sps:
        for si, sp in enumerate(sps):
            sp_vars_str   = fmt_u32_array(sp["variables"])
            sp_constr_str = "array![" + ", ".join(fmt_constraint(c) for c in sp["constraints"]) + "]"
            sp_hint_str   = fmt_u32_array(sp["min_fill_order"])
            sp_nbrs_str   = fmt_u32_array(sp["neighbor_vars"])
            x_var = sp["x_var"]
            tag = f"sp{si}" if len(sps) > 1 else "sp"
            lines.append(f"    // Step {step_num}: joint VE on special component {si} (size={len(sp['variables'])} width={sp['min_fill_width']})")
            lines.append(f"    let {tag}_vars: Array<u32> = {sp_vars_str};")
            lines.append(f"    let {tag}_constr: Array<Constraint> = {sp_constr_str};")
            lines.append(f"    let {tag}_hint: Array<u32> = {sp_hint_str};")
            lines.append(f"    let {tag}_nbrs: Array<u32> = {sp_nbrs_str};")
            lines.append(f"    let {tag}_entries: Array<JointEntry> = count_joint_component_with_order(@{tag}_vars, @{tag}_constr, {x_var}, @{tag}_nbrs, @{tag}_hint);")
            step_num += 1
        if len(sps) == 1:
            lines.append(f"    let mut aggregate: Array<JointEntry> = sp_entries;")
        else:
            lines.append(f"    let mut aggregate: Array<JointEntry> = convolve_joint(@sp0_entries, @sp1_entries);")
            for si in range(2, len(sps)):
                lines.append(f"    aggregate = convolve_joint(@aggregate, @sp{si}_entries);")
    else:
        lines.append(f"    // No special component")
        lines.append(f"    let mut aggregate: Array<JointEntry> = array![JointEntry {{ mines: 0, x_mine: 0, nbrs: 0, count: 1_u256 }}];")

    # Ordinary components
    for oi, oc in enumerate(fix["ordinary_components"]):
        ov = fmt_u32_array(oc["variables"])
        oc_str = "array![" + ", ".join(fmt_constraint(c) for c in oc["constraints"]) + "]"
        lines.append(f"    // Step {step_num}.{oi}: ordinary component {oi} (size={len(oc['variables'])})")
        lines.append(f"    let ord{oi}v: Array<u32> = {ov};")
        lines.append(f"    let ord{oi}c: Array<Constraint> = {oc_str};")
        lines.append(f"    let ord{oi}w = count_ordinary_component(@ord{oi}v, @ord{oi}c);")
        lines.append(f"    aggregate = convolve_ordinary(@aggregate, @ord{oi}w);")
        if oi == 0:
            step_num += 1

    # Unconstrained local
    if unc["has"]:
        n_unc = unc["neighbor_count"]
        lines.append(f"    // unconstrained local neighbors={n_unc}")
        lines.append(f"    aggregate = apply_unconstrained_local(@aggregate, false, {n_unc});")

    # Extract outcomes
    lines.append(f"    let {out_var} = extract_outcomes(@aggregate, {rm}, {uo}, {akm});")

    return lines


def bench_test(fix: dict, test_name: str) -> str:
    sps = fix.get("special_components", [])
    oc  = fix["ordinary_components"]
    unc = fix["unconstrained_local"]
    max_width = max((sp["min_fill_width"] for sp in sps), default=0)
    comment = (
        f"CELL gas: id={fix['flood_id']} step={fix['step']} wave={fix['wave_index']}"
        f" w={max_width} ord={len(oc)} unc_loc={unc['neighbor_count']}"
        f" unc_oth={fix['unconstrained_other_count']}"
    )
    body = cell_pipeline_lines(fix, underscore_outcomes=True)
    return (
        f"#[test]\n"
        f"// {comment}\n"
        f"fn {test_name}() {{\n"
        + "\n".join(body) + "\n"
        f"}}\n"
    )


def exact_test(fix: dict, test_name: str) -> str:
    body = cell_pipeline_lines(fix, underscore_outcomes=False)
    eo = fix["expected_outcomes"]
    case_label = f"{fix['flood_id']}_s{fix['step']:03d}"

    asserts = []
    asserts.append(f"    assert(u512_eq(*outcomes.at(0), {int_to_u512(int(eo['mine']))}), '{case_label} mine');")
    for i in range(9):
        val = int(eo.get(str(i), 0))
        asserts.append(f"    assert(u512_eq(*outcomes.at({i+1}), {int_to_u512(val)}), '{case_label} c{i}');")

    return (
        f"#[test]\n"
        f"// CELL exact: id={fix['flood_id']} step={fix['step']}\n"
        f"fn {test_name}() {{\n"
        + "\n".join(body) + "\n"
        + "\n".join(asserts) + "\n"
        f"}}\n"
    )


def main() -> None:
    fixtures: list[dict] = []
    with open(FIXTURES_PATH) as f:
        for line in f:
            if line.strip():
                fixtures.append(json.loads(line))

    # Sort by flood_index for deterministic naming
    fixtures.sort(key=lambda x: x["flood_index"])
    print(f"Loaded {len(fixtures)} fixtures", file=sys.stderr)

    bench_lines = [BENCH_HEADER]
    exact_lines = [EXACT_HEADER]

    for fix in fixtures:
        fi = fix["flood_index"]
        tname_bench = f"im_f{fi:02d}"
        tname_exact = f"im_exact_f{fi:02d}"
        bench_lines.append(bench_test(fix, tname_bench))
        exact_lines.append(exact_test(fix, tname_exact))

    BENCH_PATH.write_text("".join(bench_lines))
    EXACT_PATH.write_text("".join(exact_lines))

    print(f"Written {BENCH_PATH} ({BENCH_PATH.stat().st_size // 1024} KB)", file=sys.stderr)
    print(f"Written {EXACT_PATH} ({EXACT_PATH.stat().st_size // 1024} KB)", file=sys.stderr)
    print(f"\nRun with:", file=sys.stderr)
    print(f"  snforge test \"im_f\"       → {len(fixtures)} benchmark tests", file=sys.stderr)
    print(f"  snforge test \"im_exact_f\" → {len(fixtures)} exact tests", file=sys.stderr)


if __name__ == "__main__":
    main()
