#!/usr/bin/env python3
"""
Generate Cairo test files for Phase 6 corpus-scale min-fill campaign.

Produces TWO files from benchmarks/2g-phase6-fixtures-20260831.jsonl:

  test_ve_phase6.cairo       — gas benchmark: VE call + len assert only.
                               These are the Phase 6 gas measurements.

  test_ve_phase6_exact.cairo — correctness: same VE call + find_joint assert
                               for EVERY expected (mines, x_mine, nbrs) -> count.
                               Gas from these tests includes assertion overhead
                               and must NOT be used for the gas distribution.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

FIXTURES = Path("benchmarks/2g-phase6-fixtures-20260831.jsonl")
OUT_GAS = Path("contracts/zkmine_2g/src/tests/test_ve_phase6.cairo")
OUT_EXACT = Path("contracts/zkmine_2g/src/tests/test_ve_phase6_exact.cairo")

FIND_JOINT_HELPER = """\
fn find_joint_local(entries: @Array<zkmine_2g::ve::JointEntry>, mines: u32, x_mine: u32, nbrs: u32) -> u256 {
    let mut i: usize = 0;
    let mut found: u256 = 0;
    loop {
        if i >= entries.len() { break; }
        let e = *entries.at(i);
        if e.mines == mines && e.x_mine == x_mine && e.nbrs == nbrs {
            found = e.count;
        }
        i += 1;
    };
    found
}

"""


def safe_name(fixture_id: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "_", fixture_id)


def fmt_u32_array(items: list[int]) -> str:
    return "array![" + ", ".join(str(v) for v in items) + "]"


def fmt_constraints(constraints: list[dict]) -> str:
    parts = []
    for c in constraints:
        scope = ", ".join(str(v) for v in c["scope"])
        parts.append(f"Constraint {{ variables: array![{scope}], rhs: {c['rhs']} }}")
    return "array![" + ", ".join(parts) + "]"


def build_gas_test(rec: dict) -> str:
    """VE + len assert only — for gas benchmark."""
    name = safe_name(rec["fixture_id"])
    size = rec["size"]
    width = rec["min_fill_width"]
    n_constraints = rec["constraint_count"]
    expected_len = rec["joint_entry_count"]
    x_var = rec["x_var"] if rec["x_var"] is not None else 0xFFFFFFFF

    vars_lit = fmt_u32_array(rec["variables"])
    hint_lit = fmt_u32_array(rec["min_fill_order"])
    nbrs_lit = fmt_u32_array(rec["neighbor_vars"])
    cons_lit = fmt_constraints(rec["constraints"])

    return f"""\
#[test]
// size={size} constraints={n_constraints} width={width} expected_entries={expected_len}
fn p6_{name}() {{
    let vars: Array<u32> = {vars_lit};
    let constraints: Array<Constraint> = {cons_lit};
    let hint: Array<u32> = {hint_lit};
    let joint = count_joint_component_with_order(@vars, @constraints, {x_var}, @{nbrs_lit}, @hint);
    assert(joint.len() == {expected_len}, '{rec["fixture_id"]} len');
}}
"""


def build_exact_test(rec: dict) -> str:
    """VE + full joint_counts exact assertions — for correctness."""
    name = safe_name(rec["fixture_id"])
    size = rec["size"]
    width = rec["min_fill_width"]
    n_constraints = rec["constraint_count"]
    expected_len = rec["joint_entry_count"]
    x_var = rec["x_var"] if rec["x_var"] is not None else 0xFFFFFFFF

    vars_lit = fmt_u32_array(rec["variables"])
    hint_lit = fmt_u32_array(rec["min_fill_order"])
    nbrs_lit = fmt_u32_array(rec["neighbor_vars"])
    cons_lit = fmt_constraints(rec["constraints"])

    # Build exact count assertions
    count_asserts = []
    for key, count in sorted(rec["joint_counts"].items()):
        mines, x_mine, nbrs = map(int, key.split(","))
        label = f"{rec['fixture_id']} {key}"[:31]  # Cairo felt252 string limit
        count_asserts.append(
            f"    assert(find_joint_local(@joint, {mines}, {x_mine}, {nbrs}) == {count}, '{label}');"
        )

    asserts_block = "\n".join(count_asserts)

    return f"""\
#[test]
// size={size} constraints={n_constraints} width={width} expected_entries={expected_len}
// CORRECTNESS: verifies all {expected_len} joint entries exactly
fn p6_exact_{name}() {{
    let vars: Array<u32> = {vars_lit};
    let constraints: Array<Constraint> = {cons_lit};
    let hint: Array<u32> = {hint_lit};
    let joint = count_joint_component_with_order(@vars, @constraints, {x_var}, @{nbrs_lit}, @hint);
    assert(joint.len() == {expected_len}, '{rec["fixture_id"]} len');
{asserts_block}
}}
"""


def main() -> None:
    with open(FIXTURES) as f:
        recs = [json.loads(l) for l in f]

    recs.sort(key=lambda r: (r["size"], r["fixture_id"]))

    # --- gas benchmark file (unchanged semantics from Phase 6 run) ---
    gas_lines: list[str] = [
        "// AUTO-GENERATED by gen_phase6_cairo_tests.py — do not edit by hand\n"
        "// Phase 6 gas benchmark: VE + len assert only. Gas = VE execution cost.\n"
        "\n"
        "use zkmine_2g::ve::{\n"
        "    count_joint_component_with_order, Constraint,\n"
        "};\n"
        "\n"
    ]
    for rec in recs:
        gas_lines.append(build_gas_test(rec))
    OUT_GAS.write_text("".join(gas_lines))
    print(f"wrote {len(recs)} gas-benchmark tests to {OUT_GAS}")

    # --- exact correctness file ---
    exact_lines: list[str] = [
        "// AUTO-GENERATED by gen_phase6_cairo_tests.py — do not edit by hand\n"
        "// Phase 6 correctness: VE + ALL joint count assertions.\n"
        "// Gas from these tests includes find_joint overhead — do NOT use for gas distribution.\n"
        "\n"
        "use zkmine_2g::ve::{\n"
        "    count_joint_component_with_order, Constraint,\n"
        "};\n"
        "\n",
        FIND_JOINT_HELPER,
    ]
    for rec in recs:
        exact_lines.append(build_exact_test(rec))
    OUT_EXACT.write_text("".join(exact_lines))
    print(f"wrote {len(recs)} exact-correctness tests to {OUT_EXACT}")
    print(f"exact file size: {OUT_EXACT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
